# Theme
include themes/DeepSpace.conf

# Appearance
font_family      family="JetBrainsMono Nerd Font Mono"

font_size 12.0
disable_ligatures false

background_opacity 0.8

detect_urls yes
undercurl_style thick-dense
underline_hyperlinks hover
url_color #3D8CC4

# my cursor settings
# cursor_shape block
# cursor_blink_interval 0
# cursor_stop_blinking_after 0
# cursor_blink_interval -1 ease-in-out
# cursor_trail 10
# cursor_trail_decay 0.1 0.20

# cursor settings copied straight from linkarzu's kitty configuration
# cursor_shape beam
# cursor_beam_thickness 1.5
# cursor_underline_thickness 2.0
# cursor_blink_interval 0
# cursor_stop_blinking_after 0
# cursor_trail 1
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 0

# cursor settings copied straight from fadilix's kitty configuration
cursor_shape block
cursor_trail 3
cursor_trail_start_threshold 0
cursor_trail_decay 0.08 0.35


# Keymappings
map shift+alt+o set_background_opacity 1
map shift+alt+t set_background_opacity 0.8


# Kitty Settings
allow_remote_control yes
copy_on_select yes
dynamic_background_opacity yes
enable_audio_bell no
linux_display_server auto
listen_on unix:/tmp/kitty
mouse_hide_wait -1
shell_integration no-cursor
